chore: update project params and structure
bank-vaults/vault-operator pull request #86
Opened 2023-06-23 13:39 UTC by ramizpolic

## Overview

Fixes #44 

## Notes for reviewer

2023-06-26 05:13 UTC, sagikazarmark commented
Couple notes:

- I'd much rather split this up into smaller PRs
- deploy/crd is not quite right: those are rather CR examples
- deploy/test move doesn't feel right, especially since it's gonna be rewritten at some point in the style of the vault-secrets-webhook e2e tests
- Can't find deploy/files anywhere yet there are references to it in code

2023-06-26 08:07 UTC, ramizpolic commented
In that case, I'd recommend using `config` directory (similar to how kubebuilder does CRD generation) which can be a common parent to all mentioned resources. 
I could split into multiple PRs, but I feel it won't really matter as much since only a couple of tree changes are impactful.

2023-06-26 08:59 UTC, ramizpolic commented
> > In that case, I'd recommend using `config` directory (similar to how kubebuilder does CRD generation) which can be a common parent to all the mentioned resources.
> 
> That doesn't feel quite right either. I mean, not for _all_ (eg. tests).
> 
> Here is my recommendation:
> 
> * deploy/charts/...
> * deploy/examples -> CR examples
> * deploy/examples/base (?) -> base resources (rbac) for examples
> * deploy/examples/... -> additional directories for examples with multiple resources (alternatively: put different objects into one yaml file for these examples)

Adding to this, if we were to put `scripts` to `hack/scripts`, we could also then move `tests` to `hack/tests`, which would fit more clearly. I wanted to avoid `deploy` dir since it is used as a transient dir during resource generation.

2023-06-26 09:10 UTC, sagikazarmark commented
> Adding to this, if we were to put `scripts` to `hack/scripts`

Sounds good to me


> we could also then move `tests` to `hack/tests`

Let's not touch tests for now. As I said, I wanna move them to e2e (which is another loosly applied pattern out there) once we rewrite them using the e2e framework.

> I wanted to avoid `deploy` dir since it is used as a transient dir during resource generation.

`deploy` is a widely used pattern IMO. I generally prefer it over config.

2023-06-27 12:57 UTC, akijakya approved these changes
I left some comments but otherwise LGTM 💯

2023-06-27 12:57 UTC, akijakya commented on deploy/examples/cr-istio.yaml
> +              value: vault:secret/data/accounts/aws#AWS_SECRET_ACCESS_KEY
You could delete this as well, there are similar deployment examples in /test/deploy, also applying this whole file at once would not make sense as we need the Vault instance to be running first, then start the webhook and only after create deployments with such annotations.

2023-06-27 12:57 UTC, akijakya commented on deploy/examples/cr-istio.yaml
> +
I think you could leave this out as it is not much different from deploy/default/rbac.yaml

2023-06-27 13:49 UTC, akijakya approved these changes

2023-06-27 14:09 UTC, sagikazarmark requested changes
Couple more nits. Other than those, LGTM.

2023-06-27 14:09 UTC, sagikazarmark commented on .dockerignore
> +/Dockerfile
Please install editorconfig plugin for tailing newlines

2023-06-27 14:09 UTC, sagikazarmark commented on hack/scripts/validate-config-crud/validate-config-crud.sh
> +bank_vaults_config_file_orig="hack/scripts/validate-config-crud/vault-config.yml"
This directory can be deleted, it's not used in this project.

2023-06-27 14:09 UTC, sagikazarmark commented on .dockerignore
> +/Dockerfile
```suggestion
/deploy/
/Dockerfile
/e2e/
/hack/

/test/

```

2023-06-27 14:09 UTC, sagikazarmark commented on .yamlignore
> +/deploy/
Can we restore the original order?

2023-06-27 16:21 UTC, sagikazarmark approved these changes
LGTM thanks @ramizpolic 

Nice work!

2023-06-27 16:36 UTC, merged